# Generated by Django 4.1.1 on 2022-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('dish_type',), 'verbose_name': 'Страви'},
        ),
        migrations.AddField(
            model_name='dishtype',
            name='dish_type_access',
            field=models.BooleanField(default=True),
        ),
    ]
