# Generated by Django 4.1.1 on 2022-09-25 15:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_options_dishtype_dish_type_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main.models.Gallery.get_file_name)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
