# Generated by Django 4.1.1 on 2022-09-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ('dish_type_order',), 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('photo',), 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('dish_type', 'dish_order'), 'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='dish_type_access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='dish_type_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='dish_type_order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_is_special',
            field=models.BooleanField(default=False, verbose_name='Спеціальна'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва стави'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_order',
            field=models.SmallIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dishtype', verbose_name='Тип страви'),
        ),
    ]
