# Generated by Django 4.1.1 on 2022-10-01 16:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dishtype_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_name', models.CharField(max_length=30)),
                ('carousel_about', models.TextField()),
                ('carousel_image', models.ImageField(upload_to=main.models.Carousel.get_file_name)),
            ],
        ),
    ]
