# Generated by Django 4.1.1 on 2022-10-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_access',
            field=models.BooleanField(default=True),
        ),
    ]
