# Generated by Django 4.1.1 on 2022-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_carousel_options_carousel_carousel_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whuus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whuus_order', models.SmallIntegerField(unique=True)),
                ('whuus_title', models.CharField(max_length=20)),
                ('whuus_about', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Чому ми',
                'verbose_name_plural': 'Чому ми',
                'ordering': ('whuus_order',),
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Про нас', 'verbose_name_plural': 'Про нас'},
        ),
    ]
