# Generated by Django 4.1.1 on 2022-10-01 17:55

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_whuus_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefs_order', models.SmallIntegerField(unique=True)),
                ('chefs_name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('chefs_role', models.CharField(max_length=20, verbose_name='Роль')),
                ('chefs_twitter', models.CharField(blank=True, max_length=50, verbose_name='Твітер')),
                ('chefs_facebook', models.CharField(blank=True, max_length=50, verbose_name='Фейсбук')),
                ('chefs_instagram', models.CharField(blank=True, max_length=50, verbose_name='Інстаграм')),
                ('chefs_linkedin', models.CharField(blank=True, max_length=50, verbose_name='Лінкедін')),
                ('chefs_image', models.ImageField(upload_to=main.models.Chefs.get_file_name, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Шеф-кухар',
                'verbose_name_plural': 'Шеф-кухарі',
                'ordering': ('chefs_order',),
            },
        ),
    ]
