# Generated by Django 4.1.1 on 2022-10-01 18:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chefs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('event_order',), 'verbose_name': 'Евент', 'verbose_name_plural': 'Евенти'},
        ),
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.ImageField(default='', null=True, upload_to=main.models.Events.get_file_name),
        ),
        migrations.AddField(
            model_name='events',
            name='event_order',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
    ]
