# Generated by Django 4.1.1 on 2022-10-01 19:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_events_options_events_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_order', models.SmallIntegerField(unique=True)),
                ('test_name', models.CharField(max_length=20)),
                ('test_role', models.CharField(max_length=20)),
                ('test_about', models.CharField(max_length=200)),
                ('test_image', models.ImageField(upload_to=main.models.Testimonials.get_file_name)),
            ],
        ),
    ]
