# Generated by Django 4.1.1 on 2022-10-01 20:08

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contacts_alter_testimonials_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_end',
            field=models.TextField(blank=True, verbose_name='Про п.3'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_p1',
            field=models.TextField(verbose_name='Про п.1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_p2',
            field=models.TextField(blank=True, verbose_name='Про п.1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_p3',
            field=models.TextField(blank=True, verbose_name='Про п.2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_start_text',
            field=models.TextField(verbose_name='Епілог'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_about',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_access',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(upload_to=main.models.Carousel.get_file_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_name',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='call1',
            field=models.CharField(max_length=50, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='call2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email1',
            field=models.CharField(max_length=50, verbose_name='Мейл 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мейл 2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='location1',
            field=models.CharField(max_length=50, verbose_name='Локація 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='location2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Локація 2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='open_hours1',
            field=models.CharField(max_length=50, verbose_name='Відчинено 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='open_hours2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Відчинено 2'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_about1',
            field=models.TextField(blank=True, verbose_name='Про п.1'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_about2',
            field=models.TextField(blank=True, verbose_name='Про п.2'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_about3',
            field=models.TextField(blank=True, verbose_name='Про п.3'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_about_finish',
            field=models.TextField(blank=True, verbose_name='Епілог'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_about_start',
            field=models.TextField(verbose_name='Пролог'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_cost',
            field=models.PositiveIntegerField(verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(default='', null=True, upload_to=main.models.Events.get_file_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_order',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to=main.models.Gallery.get_file_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='test_about',
            field=models.CharField(max_length=200, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='test_image',
            field=models.ImageField(upload_to=main.models.Testimonials.get_file_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='test_name',
            field=models.CharField(max_length=20, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='test_order',
            field=models.SmallIntegerField(unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='test_role',
            field=models.CharField(max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='whuus',
            name='whuus_about',
            field=models.CharField(max_length=100, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='whuus',
            name='whuus_order',
            field=models.SmallIntegerField(unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='whuus',
            name='whuus_title',
            field=models.CharField(max_length=20, verbose_name='Заголовок'),
        ),
    ]
