# Generated by Django 4.1.1 on 2022-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreservations',
            options={'ordering': ('-date',), 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterField(
            model_name='userreservations',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
